export const YOUTUBE_TITLE_TAGS_ENGLISH = [
  "(Official Video)",
  "[Official Video]",
  "Official Video",
  "(Official Music Video)",
  "[Official Music Video]",
  "Official Music Video",
  "(Lyric Video)",
  "[Lyric Video]",
  "Lyric Video",
  "(Lyrics)",
  "[Lyrics]",
  "Lyrics",
  "(Audio)",
  "[Audio]",
  "Audio",
  "(Visualizer)",
  "[Visualizer]",
  "Visualizer",
  "(Live)",
  "[Live]",
  "Live",
  "(Acoustic)",
  "Acoustic",
  "(Acoustic Version)",
  "Acoustic Version",
  "(Extended Version)",
  "Extended Version",
  "(Performance Video)",
  "Performance Video",
  "(Remix)",
  "[Remix]",
  "Remix",
  "(Cover)",
  "[Cover]",
  "Cover",
  "(Karaoke)",
  "Karaoke",
  "(Behind The Scenes)",
  "Behind The Scenes",
  "(Official)",
  "[Official]",
  "Official",
  "(Music Video)",
  "[Music Video]",
  "Music Video",
  "(Official Audio)",
  "Official Audio",
  "(Teaser)",
  "Teaser",
  "(Trailer)",
  "Trailer",
]

export const YOUTUBE_TITLE_TAGS_SPANISH = [
  "(Video Oficial)",
  "(Vídeo Oficial)",
  "[Video Oficial]",
  "[Vídeo Oficial]",
  "Video Oficial",
  "Vídeo Oficial",
  "(Lyric Video)",
  "[Lyric Video]",
  "Lyric Video",
  "(Letra)",
  "[Letra]",
  "Letra",
  "(En Vivo)",
  "[En Vivo]",
  "En Vivo",
  "(Acústico)",
  "[Acústico]",
  "Acústico",
  "(Versión Acústica)",
  "Versión Acústica",
  "(Audio Oficial)",
  "Audio Oficial",
  "(Visualizer)",
  "Visualizer",
  "(Performance)",
  "(En Directo)",
  "En Directo",
  "Versión en Vivo",
  "(Remix)",
  "[Remix]",
  "Remix",
  "(Oficial Video)",
  "[Oficial Video]",
  "Oficial Video",
  "(Live)",
  "[Live]",
  "(Cover)",
  "[Cover]",
  "Cover",
  "(Versión Extendida)",
  "Versión Extendida",
  "(Versión Remix)",
  "Versión Remix",
  "(Behind The Scenes)",
  "(Detrás de Cámaras)",
  "Detrás de Cámaras",
  "Behind the Scenes",
  "(Con Letra)",
  "Con Letra",
  "(Subtitulado)",
  "Subtitulado",
  "(Karaoke)",
  "Karaoke",
  "(Oficial)",
  "[Oficial]",
  "Oficial",
  "(Videoclip Oficial)",
  "Videoclip Oficial",
]
