export enum ErrorTypes {
  // AppInitializer
  MISSING_ENV_VARIABLES = "MISSING_ENV_VARIABLES",
  MISSING_DEPENDENCIES = "MISSING_DEPENDENCIES",
  // DownloadSources
  GET_URLS_FROM_PLAYLIST = "GET_URLS_FROM_PLAYLIST",
  GET_URLS_FROM_GIST = "GET_URLS_FROM_GIST",
  FETCH = "FETCH",
  // Downloader
  DOWNLOAD = "DOWNLOAD",
  GET_VIDEO_DATA = "GET_VIDEO_DATA",
  // Metadater
  METADATA_AUTH = "METADATA_AUTH",
  GET_METADATA_FROM_QUERY = "GET_METADATA_FROM_QUERY",
  SET_METADATA_TO_MP3 = "SET_METADATA_TO_MP3",
  // MusicServer
  RESCAN_LIBRARY = "RESCAN_LIBRARY",
}
